name: build and run tests
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: get-cmake
      uses: lukka/get-cmake@latest
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
    - name: build with cmake
      uses: lukka/run-cmake@v3
      with:
        cmakeAppendedArgs: '-DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache'
    - name: run tests
      run: build/test_nmssearch